# Generated by Django 3.1.3 on 2020-11-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=122)),
                ('source_acc_no', models.CharField(max_length=122)),
                ('money_deposit', models.IntegerField()),
                ('destination_name', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='account_no',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='ifsc_code',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
