# Generated by Django 3.1.3 on 2020-11-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201111_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_details',
            name='Current_balance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
